# Generated by Django 3.1.7 on 2021-03-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyramid', '0004_auto_20210319_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='adds_to_payment',
            field=models.BooleanField(default=True, verbose_name='Adds to payment'),
        ),
        migrations.AlterField(
            model_name='product',
            name='adds_to_points',
            field=models.BooleanField(default=True, verbose_name='Adds to points'),
        ),
    ]
