# Generated by Django 3.1.7 on 2021-03-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyramid', '0005_auto_20210319_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='points_type',
            field=models.CharField(choices=[('production', 'Production points'), ('reward', 'Reward points'), ('fiscal', 'Fiscal points')], default='production', max_length=50, verbose_name='Points type'),
        ),
    ]
