# Generated by Django 3.1.7 on 2021-03-20 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyramid', '0006_product_points_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Calculation', 'verbose_name_plural': 'Calculations'},
        ),
    ]
