# Generated by Django 3.1.7 on 2021-03-20 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyramid', '0007_auto_20210320_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='career_points',
            field=models.FloatField(null=True, verbose_name='Total career points'),
        ),
        migrations.AddField(
            model_name='payment',
            name='compensation',
            field=models.FloatField(null=True, verbose_name='Compensation'),
        ),
        migrations.AddField(
            model_name='payment',
            name='fiscal_points',
            field=models.FloatField(null=True, verbose_name='Fiscal points'),
        ),
        migrations.AddField(
            model_name='payment',
            name='production_points',
            field=models.FloatField(null=True, verbose_name='Production points'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reward_points',
            field=models.FloatField(null=True, verbose_name='Reward points'),
        ),
    ]
