# Generated by Django 3.1.7 on 2021-03-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyramid', '0009_auto_20210320_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Amount'),
        ),
    ]
